export { default as HomeLayout} from './HomeLayout'
export { default as DashboardLayout} from './DashboardLayout'
export { default as Landing} from './Landing'
export { default as Login} from './Login'
export { default as Register} from './Register'
export { default as Error} from './Error'
export { default as Stats} from './Stats'
export { default as AddDevice} from './AddDevice'
export { default as AllDevices} from './AllDevices'
export { default as Device} from './Device'

